# Generated by Django 4.2 on 2023-05-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='abc', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='profilepic',
            field=models.FileField(default='abc', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='abc', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='profilepic',
            field=models.FileField(default='abc', upload_to=''),
            preserve_default=False,
        ),
    ]
