# Generated by Django 4.2 on 2023-05-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaid_app', '0002_doctor_name_doctor_profilepic_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='licensenum',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='address',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
